# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-23 18:03
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(choices=[('fiction', 'Fiction'), ('nonfiction', 'Noniction'), ('poetry', 'Poetry'), ('essay', 'Essay')], default='Undefined', max_length=255)),
                ('title', models.CharField(default='', max_length=255)),
                ('author', models.CharField(default='', max_length=255)),
                ('body', models.TextField(default='')),
                ('created_on', models.DateTimeField(default=datetime.datetime(2017, 7, 23, 18, 3, 21, 107915, tzinfo=utc))),
            ],
        ),
    ]
